// Generated by https://pagedraw.io/pages/13610
import React from 'react';
import './device_elements.css';


export default class Device_elements extends React.Component {
  render() {
    return (
      <div className="device_elements-device_elements-0">
          <div className="device_elements-0">
              <div className="device_elements-0-0">
                  <div className="device_elements-0-0-0">
                      <div className="device_elements-0-0-0-0">
                          <div className="device_elements-label-0">System bars</div>
                          <div className="device_elements-component_title-0" /> 
                      </div>
                  </div>
              </div>
          </div>
          <div className="device_elements-1">
              <div className="device_elements-1-0">
                  <div className="device_elements-1-0-0">
                      <div className="device_elements-1-0-0-0">
                          <div className="device_elements-various_device_android_status_bar-0">
                              <div className="device_elements-1-0-0-0-0-0">
                                  <div className="device_elements-status_bar_bg-0">
                                      <div className="device_elements-1-0-0-0-0-0-0-0">
                                          <div className="device_elements-bounds-0">
                                              <div className="device_elements-1-0-0-0-0-0-0-0-0-0">
                                                  <div className="device_elements-1-0-0-0-0-0-0-0-0-0-0">
                                                      <div className="device_elements-1-0-0-0-0-0-0-0-0-0-0-0">
                                                          <div className="device_elements-rectangle-path-0" /> 
                                                      </div>
                                                  </div>
                                                  <div className="device_elements-1-0-0-0-0-0-0-0-0-0-1">
                                                      <div className="device_elements-1-0-0-0-0-0-0-0-0-0-1-0">
                                                          <div className="device_elements-rectangle-path-00" /> 
                                                      </div>
                                                  </div>
                                                  <div className="device_elements-1-0-0-0-0-0-0-0-0-0-2">
                                                      <div className="device_elements-1-0-0-0-0-0-0-0-0-0-2-0">
                                                          <div className="device_elements-rectangle-path-000" /> 
                                                      </div>
                                                  </div>
                                                  <div className="device_elements-1-0-0-0-0-0-0-0-0-0-3">
                                                      <div className="device_elements-1-0-0-0-0-0-0-0-0-0-3-0">
                                                          <div className="device_elements-rectangle-path-0000" /> 
                                                      </div>
                                                  </div>
                                                  <div className="device_elements-1-0-0-0-0-0-0-0-0-0-4">
                                                      <div className="device_elements-1-0-0-0-0-0-0-0-0-0-4-0">
                                                          <div className="device_elements-rectangle-path-00000" /> 
                                                      </div>
                                                      <div className="device_elements-1-0-0-0-0-0-0-0-0-0-4-1">
                                                          <div className="device_elements-rectangle-path-000000" /> 
                                                      </div>
                                                      <div className="device_elements-1-0-0-0-0-0-0-0-0-0-4-2">
                                                          <div className="device_elements-rectangle-path-000003" /> 
                                                      </div>
                                                      <div className="device_elements-1-0-0-0-0-0-0-0-0-0-4-3">
                                                          <div className="device_elements-rectangle-path-000001" /> 
                                                      </div>
                                                      <div className="device_elements-1-0-0-0-0-0-0-0-0-0-4-4">
                                                          <div className="device_elements-rectangle-path-000004" /> 
                                                      </div>
                                                  </div>
                                                  <div className="device_elements-12">{"12:30"}</div>
                                              </div>
                                          </div>
                                      </div>
                                  </div>
                              </div>
                          </div>
                          <div className="device_elements-path-000001">
                              <div className="device_elements-1-0-0-0-1-0">
                                  <div className="device_elements-path-00000">
                                      <div className="device_elements-1-0-0-0-1-0-0-0">
                                          <div className="device_elements-path-0000">
                                              <div className="device_elements-1-0-0-0-1-0-0-0-0-0">
                                                  <div className="device_elements-1-0-0-0-1-0-0-0-0-0-0">
                                                      <div className="device_elements-path-0" /> 
                                                      <div className="device_elements-path-000">
                                                          <div className="device_elements-1-0-0-0-1-0-0-0-0-0-0-1-0">
                                                              <div className="device_elements-oval-0">
                                                                  <div className="device_elements-1-0-0-0-1-0-0-0-0-0-0-1-0-0-0">
                                                                      <div className="device_elements-path-00" /> 
                                                                  </div>
                                                              </div>
                                                          </div>
                                                      </div>
                                                  </div>
                                              </div>
                                          </div>
                                      </div>
                                  </div>
                              </div>
                          </div>
                      </div>
                  </div>
              </div>
          </div>
          <div className="device_elements-2">
              <div className="device_elements-2-0">
                  <div className="device_elements-2-0-0">
                      <div className="device_elements-2-0-0-0">
                          <div className="device_elements-label-00">
                              Keyboard / Input
                          </div>
                          <div className="device_elements-component_title-00" /> 
                      </div>
                  </div>
              </div>
          </div>
          <div className="device_elements-3">
              <div className="device_elements-various_device_keyboard_light-0">
                  <div className="device_elements-3-0-0">
                      <div className="device_elements-bg-0">
                          <div className="device_elements-3-0-0-0-0">
                              <div className="device_elements-3-0-0-0-0-0">
                                  <div className="device_elements-3-0-0-0-0-0-0">
                                      <div className="device_elements-suggestion-0">
                                          suggestion
                                      </div>
                                  </div>
                              </div>
                              <div className="device_elements-line-0" /> 
                              <div className="device_elements-3-0-0-0-0-2">
                                  <div className="device_elements-3-0-0-0-0-2-0">
                                      <div className="device_elements-suggestion-00">
                                          suggestion
                                      </div>
                                  </div>
                              </div>
                              <div className="device_elements-line-00" /> 
                              <div className="device_elements-3-0-0-0-0-4">
                                  <div className="device_elements-3-0-0-0-0-4-0">
                                      <div className="device_elements-suggestion-000">
                                          suggestion
                                      </div>
                                  </div>
                              </div>
                          </div>
                      </div>
                  </div>
                  <div className="device_elements-3-0-1">
                      <div className="device_elements-bg-00">
                          <div className="device_elements-3-0-1-0-0">
                              <div className="device_elements-3-0-1-0-0-0">
                                  <div className="device_elements-3-0-1-0-0-0-0">
                                      <div className="device_elements-3-0-1-0-0-0-0-0">
                                          <div className="device_elements-q-0">q</div>
                                          <div className="device_elements-1-00">1</div>
                                      </div>
                                  </div>
                              </div>
                              <div className="device_elements-3-0-1-0-0-1">
                                  <div className="device_elements-3-0-1-0-0-1-0">
                                      <div className="device_elements-3-0-1-0-0-1-0-0">
                                          <div className="device_elements-w-0">w</div>
                                          <div className="device_elements-2-00">2</div>
                                      </div>
                                  </div>
                              </div>
                              <div className="device_elements-3-0-1-0-0-2">
                                  <div className="device_elements-3-0-1-0-0-2-0">
                                      <div className="device_elements-3-0-1-0-0-2-0-0">
                                          <div className="device_elements-e-0">e</div>
                                          <div className="device_elements-3-0">3</div>
                                      </div>
                                  </div>
                              </div>
                              <div className="device_elements-3-0-1-0-0-3">
                                  <div className="device_elements-3-0-1-0-0-3-0">
                                      <div className="device_elements-3-0-1-0-0-3-0-0">
                                          <div className="device_elements-r-0">r</div>
                                          <div className="device_elements-4-0">4</div>
                                      </div>
                                  </div>
                              </div>
                              <div className="device_elements-3-0-1-0-0-4">
                                  <div className="device_elements-3-0-1-0-0-4-0">
                                      <div className="device_elements-3-0-1-0-0-4-0-0">
                                          <div className="device_elements-t-0">t</div>
                                          <div className="device_elements-5">5</div>
                                      </div>
                                  </div>
                              </div>
                              <div className="device_elements-3-0-1-0-0-5">
                                  <div className="device_elements-3-0-1-0-0-5-0">
                                      <div className="device_elements-3-0-1-0-0-5-0-0">
                                          <div className="device_elements-y-0">y</div>
                                          <div className="device_elements-6">6</div>
                                      </div>
                                  </div>
                              </div>
                              <div className="device_elements-3-0-1-0-0-6">
                                  <div className="device_elements-3-0-1-0-0-6-0">
                                      <div className="device_elements-3-0-1-0-0-6-0-0">
                                          <div className="device_elements-u-0">u</div>
                                          <div className="device_elements-7">7</div>
                                      </div>
                                  </div>
                              </div>
                              <div className="device_elements-3-0-1-0-0-7">
                                  <div className="device_elements-3-0-1-0-0-7-0">
                                      <div className="device_elements-3-0-1-0-0-7-0-0">
                                          <div className="device_elements-i-0">i</div>
                                          <div className="device_elements-8">8</div>
                                      </div>
                                  </div>
                              </div>
                              <div className="device_elements-3-0-1-0-0-8">
                                  <div className="device_elements-3-0-1-0-0-8-0">
                                      <div className="device_elements-3-0-1-0-0-8-0-0">
                                          <div className="device_elements-o-0">o</div>
                                          <div className="device_elements-9">9</div>
                                      </div>
                                  </div>
                              </div>
                              <div className="device_elements-3-0-1-0-0-9">
                                  <div className="device_elements-3-0-1-0-0-9-0">
                                      <div className="device_elements-3-0-1-0-0-9-0-0">
                                          <div className="device_elements-p-0">p</div>
                                          <div className="device_elements-0-00">0</div>
                                      </div>
                                  </div>
                              </div>
                          </div>
                          <div className="device_elements-3-0-1-0-1">
                              <div className="device_elements-a-0">a</div>
                              <div className="device_elements-s-0">s</div>
                              <div className="device_elements-d-0">d</div>
                              <div className="device_elements-f-0">f</div>
                              <div className="device_elements-g-0">g</div>
                              <div className="device_elements-h-0">h</div>
                              <div className="device_elements-j-0">j</div>
                              <div className="device_elements-k-0">k</div>
                              <div className="device_elements-l-0">l</div>
                          </div>
                          <div className="device_elements-3-0-1-0-2">
                              <div className="device_elements-3-0-1-0-2-0">
                                  <div className="device_elements-3-0-1-0-2-0-0">
                                      <div className="device_elements-shape-0" /> 
                                  </div>
                                  <div className="device_elements-3-0-1-0-2-0-1">
                                      <div className="device_elements-rectangle-path-0000039" /> 
                                  </div>
                              </div>
                              <div className="device_elements-z-0">z</div>
                              <div className="device_elements-x-0">x</div>
                              <div className="device_elements-c-0">c</div>
                              <div className="device_elements-v-0">v</div>
                              <div className="device_elements-b-0">b</div>
                              <div className="device_elements-n-0">n</div>
                              <div className="device_elements-m-0">m</div>
                              <div className="device_elements-3-0-1-0-2-8">
                                  <div className="device_elements-3-0-1-0-2-8-0">
                                      <div className="device_elements-path-0000019">
                                          <div className="device_elements-3-0-1-0-2-8-0-0-0">
                                              <div className="device_elements-path-0000012" /> 
                                          </div>
                                      </div>
                                  </div>
                              </div>
                          </div>
                          <div className="device_elements-3-0-1-0-3">
                              <div className="device_elements-3-0-1-0-3-0">
                                  <div className="device_elements-3-0-1-0-3-0-0">
                                      <div className="device_elements-_1">{"?123"}</div>
                                  </div>
                              </div>
                              <div className="device_elements-3-0-1-0-3-1">
                                  <div className="device_elements-3-0-1-0-3-1-0">
                                      <div className="device_elements-_-0">,</div>
                                  </div>
                              </div>
                              <div className="device_elements-3-0-1-0-3-2">
                                  <div className="device_elements-3-0-1-0-3-2-0">
                                      <div className="device_elements-space-0" /> 
                                  </div>
                              </div>
                              <div className="device_elements-3-0-1-0-3-3">
                                  <div className="device_elements-3-0-1-0-3-3-0">
                                      <div className="device_elements-_-00">.</div>
                                  </div>
                              </div>
                              <div className="device_elements-button_bg-0">
                                  <div className="device_elements-3-0-1-0-3-4-0">
                                      <div className="device_elements-rectangle-path-0000036">
                                          <div className="device_elements-3-0-1-0-3-4-0-0-0">
                                              <div className="device_elements-path-000000" /> 
                                          </div>
                                      </div>
                                  </div>
                              </div>
                          </div>
                      </div>
                  </div>
              </div>
          </div>
          <div className="device_elements-4">
              <div className="device_elements-various_device_android_navigation_bar-0">
                  <div className="device_elements-4-0-0">
                      <div className="device_elements-navbar_bg-0">
                          <div className="device_elements-4-0-0-0-0">
                              <div className="device_elements-back-0" /> 
                              <div className="device_elements-4-0-0-0-0-1">
                                  <div className="device_elements-4-0-0-0-0-1-0">
                                      <div className="device_elements-home-0" /> 
                                  </div>
                              </div>
                              <div className="device_elements-4-0-0-0-0-2">
                                  <div className="device_elements-4-0-0-0-0-2-0">
                                      <div className="device_elements-recent-0" /> 
                                  </div>
                              </div>
                          </div>
                      </div>
                  </div>
              </div>
          </div>
      </div>
    );
  }
};
